[package]
name = "parse_pgo_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "consts"
path = "src/consts.rs"

[dependencies]
xmltree = "0.10.3"
